# Generated by Django 5.1.2 on 2024-11-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_alter_category_name_alter_choice_question_quizresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizresult",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
